###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################

apiVersion: v1
description: A Helm chart for deploying LSF-CE worker nodes
name: lsfce-worker
version: 1.0.0
appVersion: 10.1.0
maintainers:
  - name: IBM Spectrum Computing
tillerVersion: ">=2.4.0"

