apiVersion: v1
name: repository
description: IBM Db2 Developer-C Edition 11.1.2.2 iFix002
version: 1.1.3
keywords:
- db2
- database
- sql
- amd64
- ppc64le
- s390x
- Limited
- ICP
- IKS
home: https://www.ibm.com/analytics/us/en/db2/
icon: https://raw.githubusercontent.com/Dan23/db2logo/master/content/db2logoicp-01.png
maintainers:
  - name: IBM Analytics
sources:
  - https://github.com/IBM/charts/tree/master/stable
tillerVersion: ">=2.4.0"
engine: gotpl
